// packages/cli/templates/svelte-router/components/Code.svelte
<pre class={classes}>
	{#if label}
		<span class="comment"># {label}</span>
	{/if}
	<span class="text"># {text}</span>
</pre>

<script>
	export let label = '';
	export let offset = false;
	export let text = '';

	$: classes = 'pre' + (offset ? ' offset' : '');
</script>

<style lang="{{style}}">
	%%__styles__%%
</style>

// packages/cli/templates/vue/components/Code.vue
<template>
	<pre :class="[$style.pre, { [$style.offset]: offset }]">
		<span v-if="label" :class="$style.comment" v-html="'# '+ label" />
		<span :class="$style.text" v-html="'$ ' + text" />
	</pre>
</template>

<script>
	export default {
		props: ['offset', 'label', 'text']
	}
</script>

<style module lang="{{style}}">
	%%__styles__%%
</style>
