// packages/cli/templates/react/components/Feats.js
import React from 'react';
import items from '@assets/features.json';
import style from './index.{{style}}';

function Item(props) {
	return (
		<div key={ props.title } className={ style.item }>
			<h3>{ props.title }</h3>
			<p>{ props.text }</p>
		</div>
	);
}

export default function (props) {
	return (
		<div className={ style.features }>{ items.map(Item) }</div>
	);
}

// packages/cli/templates/vue/components/Feats.vue
<template>
	<div :class="$style.features">
		<div :class="$style.item"
			v-for="item in items"
			:key="item.title"
		>
			<h3 v-html="item.title" />
			<p v-html="item.text" />
		</div>
	</div>
</template>

<script>
	import items from '@assets/features.json';

	export default {
		data() {
			return { items };
		}
	}
</script>

<style module lang="{{style}}">
	%%__styles__%%
</style>
