// packages/cli/templates/react/components/Window.js
import React from 'react';
import VIDEO from '@assets/video.svg';
import style from './index.{{style}}';

export default function (props) {
	return (
		<div className={ style.window_wrap }>
			<div className={ style.window }>
				<object data={ VIDEO } type="image/svg+xml" />
			</div>
		</div>
	);
}

// packages/cli/templates/vue/components/Window.vue
<template>
	<div :class="$style.window_wrap">
		<div :class="$style.window">
			<img :src="video" alt="recording" />
		</div>
	</div>
</template>

<script>
	import video from '@assets/video.svg';

	export default {
		data() {
			return { video };
		}
	}
</script>

<style module lang="{{style}}">
	%%__styles__%%
</style>
