// packages/cli/templates/vue-router/components/Window.vue
<template>
	<div :class="$style.window_wrap">
		<div :class="$style.window">
			<object :data="video" type="image/svg+xml">pwa init</object>
		</div>
	</div>
</template>

<script>
	import video from '@assets/video.svg';

	export default {
		data() {
			return { video };
		}
	}
</script>

<style module lang="{{style}}">
	%%__styles__%%
</style>

// packages/cli/templates/react/components/Window.js
import React from 'react';
import VIDEO from '@assets/video.svg';
import style from './index.{{style}}';

export default function (props) {
	return (
		<div className={ style.window_wrap }>
			<div className={ style.window }>
				<object data={ VIDEO } type="image/svg+xml">pwa init</object>
			</div>
		</div>
	);
}
