// packages/cli/templates/react-router/components/Nav.js
import React from 'react';
import { Link } from 'react-router-dom';
import style from './index.{{style}}';

export default class Nav extends React.Component {
	state = {
		stuck: false,
	};

	componentDidMount() {
		addEventListener('scroll', ev => {
			let stuck = window.pageYOffset > 0;
			this.setState({ stuck });
		}, { passive:true });
	}

	shouldComponentUpdate(_, nxt) {
		let now = this.state;
		return now.stuck !== nxt.stuck;
	}

	render() {
		let cls = style.nav;
		if (this.state.stuck) {
			cls += ` ${style.stuck}`;
		}

		return (
			<nav className={ cls }>
				<ul className={ style.links }>
					<li><Link to="/">Home</Link></li>
					<li><Link to="/blog">Blog</Link></li>
					<li><Link to="/about">About</Link></li>
				</ul>

				<ul>
					<li><a href="https://github.com/lukeed/pwa" className={ style.link_external }>GitHub</a></li>
					<li><a href="https://github.com/lukeed/pwa" className={ style.link_external }>Documentation</a></li>
				</ul>
			</nav>
		);
	}
}

// packages/cli/templates/vue-router/components/Nav.vue
<template>
	<nav :class="[$style.nav, { [$style.stuck]: stuck }]">
		<ul :class="$style.links">
			<li><router-link to="/">Home</router-link></li>
			<li><router-link to="/blog">Blog</router-link></li>
			<li><router-link to="/about">About</router-link></li>
		</ul>

		<ul>
			<li><a href="https://github.com/lukeed/pwa" :class="$style.link_external">GitHub</a></li>
			<li><a href="https://github.com/lukeed/pwa" :class="$style.link_external">Documentation</a></li>
		</ul>
	</nav>
</template>

<script>
	export default {
		data() {
			return {
				stuck: false
			};
		},
		mounted() {
			addEventListener('scroll', ev => {
				this.stuck = window.pageYOffset > 0;
			}, { passive:true });
		}
	}
</script>

<style module lang="{{style}}">
	%%__styles__%%
</style>
