// packages/cli/templates/svelte-router/components/App.svelte
<div class="app">
	<Hero />

	<main class="wrapper">
		<svelte:component this={ Route } { params } />
	</main>

	<Footer />
</div>

<script>
	import Navaid from 'navaid';
	import { onMount } from 'svelte';
	import Footer from '@components/Footer';
	import Hero from '@components/Hero';

	let Route, params={};

	function draw(m, params) {
		params = params || {};
		Route = m.default || m;
	}

	function track(obj) {
		if (window.ga) {
			ga.send('pageview', { dp:obj.uri });
		}
	}

	const router = (
		Navaid('/')
			.on('/', () => import('@pages/Home').then(draw))
			.on('/blog', () => import('@pages/Blog').then(draw))
			.on('/blog/:title', obj => import('@pages/Article').then(m => draw(m, obj)))
			.on('/about', () => import('@pages/About').then(draw))
	);

	onMount(() => {
		router.listen();
		addEventListener('replacestate', track);
		addEventListener('pushstate', track);
		addEventListener('popstate', track);

		return () => {
			removeEventListener('replacestate', track);
			removeEventListener('pushstate', track);
			removeEventListener('popstate', track);
			router.unlisten();
		};
	});
</script>

<style lang="{{style}}">
	%%__styles__%%
</style>

// packages/cli/templates/react-router/components/App.js
import React from 'react';
import Loadable from 'react-loadable';
import { HMR } from '@pwa/preset-react';
import { Route, withRouter } from 'react-router-dom';
import Footer from '@components/Footer';
import Hero from '@components/Hero';
import style from './index.{{style}}';

// Route-Split Components
const loading = () => <div>Loading...</div>;
const load = loader => Loadable({ loader, loading });

const Home = load(() => import('@pages/Home'));
const About = load(() => import('@pages/About'));
const Article = load(() => import('@pages/Article'));
const Blog = load(() => import('@pages/Blog'));

class App extends React.Component {
	componentDidMount() {
		if (process.env.NODE_ENV === 'production') {
			this.props.history.listen(obj => {
				if (window.ga) ga.send('pageview', { dp:obj.pathname });
			});
		}
	}

	render() {
		return (
			<div className={ style.app }>
				<Hero />

				<main className={ style.wrapper }>
					<Route path="/" exact component={ Home } />
					<Route path="/blog" exact component={ Blog } />
					<Route path="/blog/:title" component={ Article } />
					<Route path="/about" exact component={ About } />
				</main>

				<Footer />
			</div>
		);
	}
}

export default HMR(withRouter(App), module);
