// packages/cli/templates/react/components/Code.js
import React from 'react';
import style from './index.{{style}}';

export default function (props) {
	let cls = style.pre;
	if (props.offset) cls += ` ${style.offset}`;
	return (
		<pre className={ cls }>
			{ props.label && <span className={ style.comment }># { props.label }</span> }
			<span className={ style.text }>$ { props.text }</span>
		</pre>
	);
}

// packages/cli/templates/svelte-router/components/Code.svelte
<pre class={classes}>
	{#if label}
		<span class="comment"># {label}</span>
	{/if}
	<span class="text"># {text}</span>
</pre>

<script>
	export let label = '';
	export let offset = false;
	export let text = '';

	$: classes = 'pre' + (offset ? ' offset' : '');
</script>

<style lang="{{style}}">
	%%__styles__%%
</style>
