// packages/cli/templates/vue-router/components/Nav.vue
<template>
	<nav :class="[$style.nav, { [$style.stuck]: stuck }]">
		<ul :class="$style.links">
			<li><router-link to="/">Home</router-link></li>
			<li><router-link to="/blog">Blog</router-link></li>
			<li><router-link to="/about">About</router-link></li>
		</ul>

		<ul>
			<li><a href="https://github.com/lukeed/pwa" :class="$style.link_external">GitHub</a></li>
			<li><a href="https://github.com/lukeed/pwa" :class="$style.link_external">Documentation</a></li>
		</ul>
	</nav>
</template>

<script>
	export default {
		data() {
			return {
				stuck: false
			};
		},
		mounted() {
			addEventListener('scroll', ev => {
				this.stuck = window.pageYOffset > 0;
			}, { passive:true });
		}
	}
</script>

<style module lang="{{style}}">
	%%__styles__%%
</style>

// packages/cli/templates/svelte-router/components/Nav.svelte
<nav class={classes}>
	<ul class="links">
		<li><a href="/">Home</a></li>
		<li><a href="/blog">Blog</a></li>
		<li><a href="/about">About</a></li>
	</ul>

	<ul>
		<li><a href="https://github.com/lukeed/pwa" class="link_external">GitHub</a></li>
		<li><a href="https://github.com/lukeed/pwa" class="link_external">Documentation</a></li>
	</ul>
</nav>

<script>
	import { onMount } from 'svelte';

	let stuck = false;

	function onScroll(ev) {
		stuck = window.pageYOffset > 0;
	}

	$: classes = 'nav' + (stuck ? ' stuck' : '');

	onMount(() => {
		addEventListener('scroll', onScroll, { passive:true });

		return () => {
			removeEventListener('scroll', onScroll);
		}
	});
</script>

<style lang="{{style}}">
	%%__styles__%%
</style>
